# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
 
  desc 'Building'
  lane :build_for_testing do
    scan(
	build_for_testing: true
    )
  end

  desc 'Run tests' 
  lane :run_tf_tests do
    run_tests(
	derived_data_path: "DerivedData/TinkoffFintech",
	test_without_building: true
    )
  end

  desc 'Build and test'
  lane :build_and_test do
    build_for_testing
    run_tests
  end
end
